### ISSUE TITLE
Input using simple forms

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swa-teaching/Scamper#175]
As a user I want to use simple input fields like the google or wikipedia searchbar 

predicted: 8

Acceptance Criteria:

- [x]  Forms should not throw an error
- [ ]  A Request with the form data should be sent

**Comment by mlichtblau** [comment]
Acceptance Criteria:

- [ ] Forms should not throw an error
- [ ] A Request with the form data should be sent

**Comment by konstantinjdobler** [comment]
This is already implemented but bugged. First two bugs are already fixed on the branch but there is another big one: In `Scamper>>submitFormWithInputsAsync: inputs url: url method: method encoding: encoding` we call `self processDocument: document` at the end of the method. `document` is expected to be a MIMEDocument but in our case it is a WebResponse.

**Comment by konstantinjdobler** [comment]
This other bug is fixed by converting to a `MIMEDocument` and we get no more error messages. However in the case of google.com our oiginal intent does not work, as apparently our input in the form does not matter and we just get sent to `google.com/search`

**Comment by konstantinjdobler** [comment]
In `Scamper>>submitFormWithInputsAsync: inputs url: url method: method encoding: encoding` we have to correctly assemble the new url by adding the form input as arguments. This is done now, test by searching on (https://duckduckgo.com/). You will get a page resulting from your input. google.com is not working because of another CSSRendering Error.
